name: unicorn-binance-suite
dependencies:
- python>=3.7.0
- pip:
  - unicorn-fy
  - unicorn-binance-local-depth-cache
  - unicorn-binance-rest-api
  - unicorn-binance-trailing-stop-loss
  - unicorn-binance-websocket-api
  
