{% set name = "unicorn-binance-suite" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: .

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

channels:
  - lucit
  - conda-forge
  - default

requirements:
  host:
    - python
    - lucit::lucit-licensing-python = ">=1.8.1"
    - lucit::unicorn-fy = ">=0.13.1"
    - lucit::unicorn-binance-local-depth-cache = ">=1.0.0"
    - lucit::unicorn-binance-rest-api = ">=2.1.2"
    - lucit::unicorn-binance-websocket-api = ">=2.1.2"
    - lucit::unicorn-binance-trailing-stop-loss = ">=1.0.0"
  run:
    - python
    - lucit::lucit-licensing-python = ">=1.8.1"
    - lucit::unicorn-fy = ">=0.13.1"
    - lucit::unicorn-binance-local-depth-cache = ">=1.0.0"
    - lucit::unicorn-binance-rest-api = ">=2.1.2"
    - lucit::unicorn-binance-websocket-api = ">=2.1.2"
    - lucit::unicorn-binance-trailing-stop-loss = ">=1.0.0"

dependencies:
  - anaconda-client
  - conda-build

test:
  imports:
    - unicorn_binance_suite
  commands:
    - pip check
  requires:
    - pip

about:
  summary: | 
    An unofficial Python API to use the Binance REST API`s (com+testnet, com-margin+testnet, 
    com-isolated_margin+testnet, com-futures+testnet, us, tr) in a easy, fast, flexible, robust and fully-featured way.
  description: |

  dev_url: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-suite
  doc_url: https://unicorn-binance-suite.docs.lucit.tech
  home: https://www.lucit.tech/unicorn-binance-suite.html
  license: LSOSL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - oliver-zehentleitner
