name: Bug report
description: Report a bug with this library.
labels: bug
body:
  - type: markdown
    attributes:
      value: | 
        Please post here only issues concerning this repository and follow the [Issue-Guidelines](https://github.com/LUCIT-Systems-and-Development/unicorn-binance-suite/wiki/Issue-Guidelines). 
        
        Most of these fields are not mandatory, but please provide as much information as possible.
  - type: textarea
    id: Version
    attributes:
      label: Version of this library.
      description: |
        Please control what version you are using with [this script](https://github.com/LUCIT-Systems-and-Development/unicorn-binance-suite/blob/master/tools/get_versions_of_unicorn_packages.py) and post the output:
    validations:
      required: true
      
  - type: checkboxes
    id: Confirmation
    attributes:
      label: Solution to Issue cannot be found in the documentation or other Issues and also occurs in the latest version of this library.
      description: |
        I have searched for other Issues with the same problem or similar feature requests and have looked in the documentation. This issue also affects the latest version of this library. 
      options:
        - label: I checked the documentation and other Issues. I am using the latest version of this library.
          required: true
      
  - type: textarea
    id: Issue
    attributes:
      label: Issue
      description: |
        Please describe the issue you are experiencing:
    validations:
      required: true
      
