name: Bug report
description: Report a bug with this library.
labels: bug
assignees:
  - oliver-zehentleitner
body:
  - type: markdown
    attributes:
      value: | 
        Please post here only issues concerning this repository and follow the [Issue-Guidelines](https://github.com/LUCIT-Systems-and-Development/unicorn-binance-suite/wiki/Issue-Guidelines). 
      
  - type: checkboxes
    id: Confirmation
    attributes:
      label: Solution to Issue cannot be found in the documentation or other Issues and also occurs in the latest version of this library.
      description: |
        I have searched for other Issues with the same problem or similar feature requests and have looked in the documentation. This issue also affects the latest version of this library. 
      options:
        - label: I checked the documentation and other Issues. I am using the latest version of this library.
          required: true
      
  - type: textarea
    id: Issue
    attributes:
      label: Issue
      description: |
        Please describe the issue you are experiencing:
    validations:
      required: true
      
