name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coveralls

    - name: Unit test
      env:
          LUCIT_API_SECRET: ${{ secrets.LUCIT_API_SECRET }}
          LUCIT_LICENSE_TOKEN: ${{ secrets.LUCIT_LICENSE_TOKEN }}
      run: coverage run --source unicorn_binance_suite unittest_binance_suite.py

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: unittests
        name: codecov-umbrella
        verbose: true
